site_name: Basalt
site_url: http://localhost:8000/
copyright: |
  <div style="display: flex">Made with <div class="heart">❤️


site_description: Basalt is a comprehensive suite of packages specifically designed for backend development in Node.js
repo_url: https://github.com/Basalt-Lab
repo_name: Basalt


theme:
  name: material
  logo: public/logo.png
  favicon: public/logo.png
  language: en
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - header.autohide
    - content.tabs.link

plugins:
  - search
  - offline
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: fr
          name: Français
          build: true
          default: false
  - termynal
markdown_extensions:
  - admonition
  - pymdownx.details

  - attr_list
  - md_in_html


  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.tabbed:
      alternate_style: true

  - tables

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - footnotes

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/driver.js@1.0.1/dist/driver.css
extra_javascript:
  - js/searchBar.js
  - js/driver.js.iife.js
  - js/driver.js


extra:
  generator: false
nav:
  - Basalt: index.md
  
  - Basalt Auth:
      - Basalt Auth: basalt-auth/index.md
      - Getting Started: basalt-auth/getting-started.md
      - References: basalt-auth/references.md
      - Example:
          - Authentication: basalt-auth/example/authentication.md
      - Contribution: basalt-auth/contribution.md

  - Basalt Helper:
      - Basalt Helper: basalt-helper/index.md
      - Getting Started: basalt-helper/getting-started.md
      - References: basalt-helper/references.md
      - Example:
          - Data:
            - BasaltData: basalt-helper/example/data/basalt-data.md
          - Security:
            - BasaltSecurity: basalt-helper/example/security/basalt-security.md
          - Utility:
            - BasaltUtility: basalt-helper/example/utility/basalt-utility.md
      - Contribution: basalt-helper/contribution.md

  - Basalt Logger:
      - Basalt Logger: basalt-logger/index.md
      - Getting Started: basalt-logger/getting-started.md
      - References: basalt-logger/references.md
      - Example:
          - Logger: basalt-logger/example/logger.md
      - Contribution: basalt-logger/contribution.md


