site_name: Basalt
site_url: http://localhost:8000/
copyright: |
  &copy; 2023-2024 Basalt


site_description: Basalt is a comprehensive suite of packages specifically designed for backend development in Node.js
repo_url: https://github.com/Basalt-Lab
repo_name: Basalt


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  language: en
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - header.autohide
    - content.tabs.link


plugins:
  - search
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: fr
          name: Français
          build: true
          default: false
  - termynal
markdown_extensions:
  - admonition
  - pymdownx.details

  - attr_list
  - md_in_html


  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.tabbed:
      alternate_style: true

  - tables

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - footnotes

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr


nav:
  - Basalt: index.md
  - Basalt Core:
      - Basalt Core: basalt-core/index.md
      - Getting Started:
          - Getting Started: basalt-core/getting-started/index.md
          - Example:
              - Data Filter: basalt-core/getting-started/example/data-filter.md
              - Password: basalt-core/getting-started/example/password.md
      - Reference:
          - Data Filter: basalt-core/reference/data-filter.md
          - Password: basalt-core/reference/password.md
      - Contribution: basalt-core/contribution.md
      - Changelog: basalt-core/changelog.md
      - License: basalt-core/license.md
  - Basalt Auth:
      - Basalt Auth: basalt-auth/index.md
      - Getting Started:
          - Getting Started: basalt-auth/getting-started/index.md
          - Example:
              - Data Filter: basalt-auth/getting-started/example/data-filter.md
              - Password: basalt-auth/getting-started/example/password.md
      - Reference:
          - Data Filter: basalt-auth/reference/data-filter.md
          - Password: basalt-auth/reference/password.md
      - Contribution: basalt-auth/contribution.md
      - Changelog: basalt-auth/changelog.md
      - License: basalt-auth/license.md
